    [build]
  command = "npm run build"
  publish = "build"
  
  [context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"
  
    [[redirects]]
  from = "/api/*"
  to = "http://ec2-3-39-12-49.ap-northeast-2.compute.amazonaws.com:8080/:splat"
  status = 200
  force = true
    [[redirects]]
  from = "/ws/*"
  to = "ws://ec2-3-39-12-49.ap-northeast-2.compute.amazonaws.com:8080/ws/websocket"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
