spring:
  redis:
    port: 6379
    host: localhost
    password: ${redis-password}
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:mysql://main-ui-db.cme0fy03xlfx.ap-northeast-2.rds.amazonaws.com:13306/main_ui_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ${DB.USERNAME}
    password : ${DB.PASSWORD}
    #url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql
#        show_sql: true

  batch:
    job:
      enabled: false # 시작과 동시에 실행되는 건 방지