spring:
  redis:
    port: 6379
    host: localhost
    password: ${redis-password}
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: ${DB.URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ${DB.USERNAME}
    password : ${DB.PASSWORD}
    #url: jdbc:h2:mem:test

  #S3 업로드
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql
#        show_sql: true

  batch:
    job:
      enabled: false # 시작과 동시에 실행되는 건 방지

cloud:
  aws:
    credentials:
      access-key: ${S3.ACCESSKEY}
      secret-key: ${S3.SECRETKEY}
    s3:
      bucket: ${S3.BUCKET}
      member: ${S3.MEMBER}
      pet: ${S3.PET}
    region:
      static: ${S3.REGION}
    stack:
      auto: false